### ISSUE TITLE
Feedback from AnuBanga

### ISSUE THREAD

**Issue by AnuBanga** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#101]
Good Work! I have few feedback points that might help you to make it even better.

**Larger Points of Feedback:-**
 - [ ] I could not clone the repository with the command given in the Readme. You can consider giving something like "git clone https://github.com/UBC-MDS/DSCI-532_2024_19_food-price-tracker.git" #119 
 - [ ] Plots are not getting displayed locally as there is package mismatch issue. Getting error RuntimeError: The versions of the vegafusion and vegafusion-python-embed packages must match and must be version 1.5.0 or greater. Found: vegafusion==1.6.6  and vegafusion-python-embed==1.6.7. However, this issue is not there on deployed dash. #121 
 - [ ] The plots are not updated quickly with filter changes. It takes some time to update filters and plots. But sometimes, they get stuck and don't change at all, and they need to be changed again to make it work.

**Smaller Points of Feedback:-**
 - [ ] gif attached in the Readme is different from the current version. You can include gif as per latest version. #122 
 - [ ] When we select the End date to change, the calendar always opens for the start date. This creates some confusion with the data range selection. 
 - [ ] Using the calendar can be tricky when the start and end dates are many years apart. A more user-friendly method for adjusting dates over more extended periods, like editing manually, would be helpful. Editing in the date field does not work at this time.

**Comment by JohnShiuMK** [comment]
duplicated in #106, closed
