### ISSUE TITLE
(milestone 2) 6. Improve README

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#31]
Include motivation behind your project and clearly explain what problem you are solving and why it is important.

You do not have to include detailed usage instructions, just high level what they can do in your dashboard and and the deployed link.

[This is a good example](https://github.com/KirstieJane/STEMMRoleModels)

**Comment by celestezhao** [comment]
6. Improve the README

rubric={reasoning:5}

Expand on the README file to be a welcoming place for anyone coming to your project for the first time. For your project, your README should cater to at least two groups of people:

1. Those interested in using your dashboard

- [x] Include motivation behind your project and clearly explain what problem you are solving and why it is important.
- [x] You do not have to include detailed usage instructions, just high level what they can do in your dashboard and the deployed link.
- [This is a good example](https://github.com/KirstieJane/STEMMRoleModels)
- [x] Include a link to your demo GIF in the README. It's sparks interest to see a demo of the app right away.
- [x] Include a note on how to get support (e.g. opening an issue).

2. Those interesting in running the app locally, and potentially helping you develop your dashboard

- [x] Potential contributors are interested in the above as well, but also need to know how they can install your app/dependencies and how to run it locally.
- [x] Include a link to the contributing file, where they can find out more if they are interested in making contributions to the repo.

**Comment by srfrew** [comment]
Readme is updated and ready to be merged
