### ISSUE TITLE
Milestone 2 Submission Requirements

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#37]
- [x] Create a 0.2.0 GitHub release w/ release notes (use CI/CD & temporarily waive main branch protection)
- [x] Submit `link-to-release.ipynb` with: 
    - [x] Single markdown cell linking to GitHub release
    - [x] Indicate whether challenging question was attempted
