### ISSUE TITLE
To be fixed in Milestone 3

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#59]
- Week 2:
- [x] #60
- [x] #63

- [x] https://github.com/UBC-MDS/DSCI-532_2024_19_food-price-tracker/issues/51

- Later Week:
- [x] #64
- [x] start-date adjustment does not trigger refresh
- [x] empty default graph caused by the non-existence of commodity in some market -> probably cannot be solved by a hierarchy of widgets
- [x] Relatively slow update time for the charts, different charts are not updated at the same time 
- [x] #83

**Comment by JohnShiuMK** [comment]
we've got everything in the github issues, closed
