### ISSUE TITLE
Milestone 1 submission checklist

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#9]
- Create a release on GitHub.com](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) with the following requirements:
    - [x] Increment the minor version number for each milestone. So for M1, the release should be named 0.1.0, for M2, 0.2.0, and so on (you're free to make patch releases in between milestones if you want to practice, e.g., 0.1.1, 0.1.2, etc).
    - [x] Include release notes. (should be able to automatically generate when releasing, to be discussed)

 - submit two files on gradescope
    - [x] link-to-release.ipynb: Includes a single markdown cell with the link to your M1 release on GitHub.
    - [x] teamwork-contract.md: Teamwork contract

**Comment by srfrew** [comment]
Submitted to gradescope!
